org.gradle.jvmargs=-Xmx1536m -Xms256m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=96m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseSerialGC -Dorg.gradle.vfs.watch=false
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx384m
android.enableNativeDebugMetadata=false
android.lint.checkReleaseBuilds=false
android.useAndroidX=true
