org.gradle.jvmargs=-Xmx2048m -Xms512m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.vfs.watch=false
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx384m
android.enableNativeDebugMetadata=false
android.lint.checkReleaseBuilds=false
android.useAndroidX=true
