<?php

namespace App\Mail;

use App\Models\Payment;
use App\Models\Sale;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * Payment receipt email.
 * TODO when API key is available: attach PDF receipt generated by ReceiptPdfService.
 */
class PaymentReceiptMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public Sale    $sale,
        public Payment $payment,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "✅ Reçu de paiement — {$this->payment->receipt_number}",
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.payment-receipt',
            with: [
                'sale'      => $this->sale->load(['client', 'schedules']),
                'payment'   => $this->payment,
                'remaining' => $this->sale->remaining_amount,
                'shopName'  => $this->sale->shop?->name ?? config('app.name'),
            ],
        );
    }

    public function attachments(): array
    {
        // PDF attachment hook — populate when PDF service is ready
        // return [Attachment::fromPath($pdfPath)->as('recu-' . $this->payment->receipt_number . '.pdf')];
        return [];
    }
}
